### ISSUE TITLE
Add storage manager service

### ISSUE THREAD

**Issue by RossComputerGuy** [ExpidusOS/gokai#5]
We should support storage management and expose it in Dart as `dart:io` compatible file system entities. On Linux, we can use gvfs. This is a necessary enhancement to port the file manager to Gokai.

# Tasks

## SDK

- [x] core: add storage manager interface
- [x] core: add filesystem interface
- [x] linux: add gvfs dependency and storage manager service

## Dart-side

- [x] Add storage manager abstract interface
- [x] Add native storage manager implementation
- [x] Add web storage manager implementation (likely use a mock or memory fs)
